#!/bin/bash

echo "================================================"
echo "Manual SSH Key Setup for macOS VM"
echo "================================================"
echo ""
echo "Step 1: Copy this public key:"
echo "-------------------------------------------"
cat ~/.ssh/macos_vm.pub
echo "-------------------------------------------"
echo ""
echo "Step 2: SSH into macOS VM:"
echo "   ssh -p 2222 localhost"
echo ""
echo "Step 3: In macOS, run these commands:"
echo "   mkdir -p ~/.ssh"
echo "   chmod 700 ~/.ssh"
echo "   echo 'PASTE_THE_KEY_HERE' >> ~/.ssh/authorized_keys"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "Or use this one-liner (replace YOUR_KEY with the key above):"
echo "   mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo 'YOUR_KEY' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "================================================"
